services:
  latex:
    build: .
    command: dev
    ports:
     - "8080:8080"
    volumes:
     - .:/app/latex-on-http
     - ./tools:/app/latex-on-http/tools
    environment:
      CACHE_HOST: cache
      # KEEP_WORKSPACE_DIR: 1
      KEEP_WORKSPACE_DIR_ON_ERROR: 1
      GOOSE_DBSTRING: postgres://latexonhttp:latexdev@postgres_db:5432/latexonhttp
  cache:
    build:
      context: .
      dockerfile: cache.Dockerfile
    volumes:
     - .:/app/latex-on-http
