# Latex On HTTP Docker container.
# Vanilla Latex installation.

# TODO Factorize further with the main Dockerfile: only the base image and
# Texlive install changes.

# Ensure this is a Vanilla Latex install.
# https://tex.stackexchange.com/questions/1092/how-to-install-vanilla-texlive-on-debian-or-ubuntu
# https://www.tug.org/texlive/debian.html
FROM rchurchley/texlive:latest
MAINTAINER Yoan Tournade <yoan@ytotech.com>

COPY ./container/install_python.sh /tmp/install_python.sh
RUN /tmp/install_python.sh

# Clean APT cache.
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

COPY ./container/install_latex_packages.sh /tmp/install_latex_packages.sh
RUN /tmp/install_latex_packages.sh

# Create app directory.
RUN \
    mkdir -p /home/latex-on-http

# Copy application source code.
# (TODO Or use a mount point? Or use pip install?)
COPY ./Makefile ./requirements.txt /home/latex-on-http/
COPY ./latex-on-http/ /home/latex-on-http/latex-on-http/

WORKDIR /home/latex-on-http/
RUN make install

EXPOSE 8080
CMD ["make", "start"]
