services:
  latex:
    build: .
    # restart: always
    # command: prod
    ports:
     - "8080:8080"
    volumes:
     - .:/app/latex-on-http
     - ./tools:/app/latex-on-http/tools
    environment:
      # SENTRY_DSN: 
      CACHE_HOST: cache
      # KEEP_WORKSPACE_DIR: 1
      KEEP_WORKSPACE_DIR_ON_ERROR: 1
      GOOSE_DBSTRING: postgres://latexonhttp:latexdev@postgres_db:5432/latexonhttp
    depends_on:
      - cache
      - postgres_db
  cache:
    build:
      context: .
      dockerfile: cache.Dockerfile
    # restart: always
    volumes:
     - .:/app/latex-on-http
    # environment:
      # SENTRY_DSN: 
    depends_on:
      - postgres_db
  postgres_db:
    image: docker.io/postgres:17
    environment:
      POSTGRES_USER: latexonhttp
      POSTGRES_PASSWORD: latexdev
      POSTGRES_DB: latexonhttp
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  adminer:
    image: docker.io/shyim/adminerevo:4.8.4
    ports:
      - 8092:8080
    environment:
      ADMINER_DEFAULT_DRIVER: pgsql
      ADMINER_DEFAULT_SERVER: postgres_db
      ADMINER_DEFAULT_USER: latexonhttp
      ADMINER_DEFAULT_PASSWORD: latexdev
      ADMINER_DEFAULT_DB: latexonhttp
      # ADMINER_DESIGN: nette
      # https://www.adminer.org/plugins/
      ADMINER_PLUGINS: tables-filter tinymce json-column
    links:
      - postgres_db
